apiVersion: v1
kind: Pod
metadata:
  name: busy-pod-deployment
  labels:
    app: busy
spec:
  containers:
    - name: busy-pod
      image: busybox:latest
      command: ["sh","-c","echo hello k8s! && sleep 3600"]

