---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-np
  labels:
    app: httpd-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-2
  template:
    metadata:
      name: httpd-service
      labels:
        app: httpd-2
    spec:
      containers:
        - name: httpd-container
          image: httpd:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: httpd-np-service
  labels:
    app: httpd-2
spec:
  selector:
    app: httpd-2
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
    